apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: passmower

manifests:
  rawYaml:
    - kube/deployment.yaml

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: passmower
          docker:
            target: dev
          sync:
            manual:
              - src: 'src/**'
                dest: .
              - src: 'frontend/src/**'
                dest: .
              - src: 'styles/src/**'
                dest: .
    deploy:
      kubectl: {}

#portForward:
#  - resourceType: deployment
#    resourceName: passmower-dev
#    port: 9229
#    localPort: 9229
