---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-gateway
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
    - host: gateway-gab7y.codemowers.ee
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: oidc-gateway
                port:
                  number: 3000
  tls:
    - hosts:
        - "*.codemowers.ee"

---
apiVersion: v1
kind: Service
metadata:
  name: oidc-gateway
spec:
  type: ClusterIP
  selector:
    app: oidc-gateway
  ports:
    - protocol: TCP
      port: 3000
      name: http
    - protocol: TCP
      port: 9090
      name: metrics
---
apiVersion: batch/v1
kind: Job
metadata:
  name: oidc-key-manager
spec:
  template:
    spec:
      serviceAccountName: oidc-gateway
      containers:
        - name: oidc-key-manager
          image: passmower
          command: [ '/app/node_modules/.bin/key-manager', 'initialize', '-c', 'cluster' ]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-gateway
  labels:
    app: oidc-gateway
spec:
  selector:
    matchLabels:
      app: oidc-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: oidc-gateway
    spec:
      serviceAccountName: oidc-gateway-dev
      containers:
        - name: oidc-gateway
          image: passmower
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9090
              name: metrics
          env:
            - name: ISSUER_URL
              value: 'https://gateway-gab7y.codemowers.ee/'
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: GROUP_PREFIX
              value: 'codemowers'
            - name: ADMIN_GROUP
              value: 'github.com:codemowers:admins'
            - name: REQUIRED_GROUP
              value: 'codemowers:users'
            - name: GITHUB_ORGANIZATION
              value: 'codemowers'
            - name: ENROLL_USERS
              value: 'true'
            - name: NAMESPACE_SELECTOR
              value: 'veebkolm-*'
            - name: PREFERRED_EMAIL_DOMAIN
              value: 'veebkolm.ee'
            - name: REQUIRE_CUSTOM_USERNAME
              value: 'true'
          envFrom:
            - secretRef:
                name: redis-oidc-gateway-owner-secrets
            - secretRef:
                  name: oidc-keys
            - secretRef:
                name: email-credentials
            - secretRef:
                name: github-client
            - secretRef:
                name: slack-client
          readinessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: 3000
              httpHeaders:
                - name: x-forwarded-for # suppress oidc-provider warning
                  value: 'https://gateway-gab7y.codemowers.ee/'
                - name: x-forwarded-proto # suppress oidc-provider warning
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 1
#          volumeMounts:
#            - mountPath: /app/tos
#              name: tos
#            - mountPath: /app/approval
#              name: approval
#            - mountPath: /app/src/views/custom/emails
#              name: email-templates
#      volumes:
#        - name: tos
#          configMap:
#            name: oidc-gateway-tos-v1
#        - name: approval
#          configMap:
#            name: oidc-gateway-approval-required
#        - name: email-templates
#          configMap:
#            name: oidc-gateway-email-templates
