---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passmower
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: veebkolm.eu
spec:
  rules:
    - host: passmower-dev.veebkolm.eu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: passmower
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: passmower
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: passmower
  ports:
    - protocol: TCP
      port: 3000
      name: http
    - protocol: TCP
      port: 9090
      name: metrics
---
apiVersion: batch/v1
kind: Job
metadata:
  name: oidc-key-manager
spec:
  template:
    spec:
      serviceAccountName: passmower-dev
      containers:
        - name: oidc-key-manager
          image: passmower
          command: [ '/app/node_modules/.bin/key-manager', 'initialize', '-c', 'cluster' ]
      restartPolicy: Never
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: passmower
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passmower
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passmower-dev
  labels:
    app.kubernetes.io/name: passmower
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passmower
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passmower
    spec:
      serviceAccountName: passmower-dev
      containers:
        - name: passmower
          image: passmower
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 9090
              name: metrics
          env:
            - name: ISSUER_URL
              value: 'https://passmower-dev.veebkolm.eu/'
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: GROUP_PREFIX
              value: 'codemowers'
            - name: ADMIN_GROUP
              value: 'github.com:veebkolm-ee:admins'
            - name: REQUIRED_GROUP
              value: 'github.com:veebkolm-ee:admins'
            - name: GITHUB_ORGANIZATION
              value: 'veebkolm-ee'
            - name: ENROLL_USERS
              value: 'true'
            - name: NAMESPACE_SELECTOR
              value: '*'
            - name: PREFERRED_EMAIL_DOMAIN
              value: 'veebkolm.ee'
            - name: REQUIRE_CUSTOM_USERNAME
              value: 'true'
            - name: NORMALIZE_EMAIL_ADDRESSES
              value: 'true'
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: redis-passmower-owner-secrets
                  key: REDIS_MASTER_0_URI
          envFrom:
            - secretRef:
                  name: oidc-keys
            - secretRef:
                name: email-credentials
            - secretRef:
                name: github-client
          readinessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: 3000
              httpHeaders:
                - name: x-forwarded-for # suppress oidc-provider warning
                  value: 'https://passmower-dev.veebkolm.eu/'
                - name: x-forwarded-proto # suppress oidc-provider warning
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 1
#          volumeMounts:
#            - mountPath: /app/tos
#              name: tos
#            - mountPath: /app/approval
#              name: approval
#            - mountPath: /app/src/views/custom/emails
#              name: email-templates
#      volumes:
#        - name: tos
#          configMap:
#            name: passmower-tos-v1
#        - name: approval
#          configMap:
#            name: passmower-approval-required
#        - name: email-templates
#          configMap:
#            name: passmower-email-templates
