---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: oidc-key-rotate
spec:
  schedule: "0 4 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: oidc-key-manager
              image: codemowers/passmower
              command: [ '/app/node_modules/.bin/key-manager', 'rotate', '--both', '-c', 'cluster', '--restart-deployment', 'oidc-gateway' ]
          serviceAccountName: oidc-key-manager
          restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-key-manager
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
      - update
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-key-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oidc-key-manager
subjects:
  - kind: ServiceAccount
    name: oidc-key-manager
    namespace: veebkolm-gab7y
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-key-manager
