---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-gateway-tos-v1
data:
  tos.md: |
    # Terms of service
    ## 1. Section
    Welcome to [oidc-gateway](https://github.com/codemowers/oidc-gateway)!
    
    ### 1.2 Conditions
    You agree to the conditions.
    
    #### 1.2.3
    You agree to the conditions.
    
    ##### 1.2.3.4
    You agree to the conditions.
    
    ###### 1.2.3.4.5
    And the points are:
      - one
      - tho
      - three
  tos.txt: |
    Lorem ipsum.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-gateway-approval-required
data:
  approval.txt: |
    You need to be approved to continue.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-gateway-email-templates
data:
  tos.txt: |
    Hi, <%= name %>!
  
    You agreed with the Terms of Service at <%= timestamp %>

    Content SHA256 hash: <%= hash %>
  
    Best regards,
    DEV
  tos.ejs: |
    <div>
        <p>Hi, <%= name %>!</p>
        <p>You agreed with the following Terms of Service at <%= timestamp %></p>
        <p>Content SHA256 hash: <%= hash %></p>
        <br />
        <blockquote>
            <%- content -%>
        </blockquote>
        <br />
        <p>Best regards, <br/> DEV</p>
    </div>
  tos.subject: |
    Terms of Service agreement confirmation
