apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "passmower.fullname" . }}
  labels:
    {{- include "passmower.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "passmower.fullname" . }}
  labels:
    {{- include "passmower.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
    apiGroups:
      - codemowers.cloud
    resources:
      - oidcusers
      - oidcusers/status
      - oidcclients
      - oidcclients/status
      - oidcmiddlewareclients
      - oidcmiddlewareclients/status
  - verbs:
      - get
      - create
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - create
      - update
      - patch
      - delete
    apiGroups:
      - traefik.io
    resources:
      - middlewares
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "passmower.fullname" . }}
  labels:
    {{- include "passmower.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "passmower.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "passmower.fullname" . }}
