{{- if not .Values.passmower.texts.terms_of_service.configMapRef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "passmower.fullname" . }}-tos
data:
  tos.md: "{{ .Values.passmower.texts.terms_of_service.content }}"
{{- end }}
---
{{- if not .Values.passmower.texts.approval.configMapRef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "passmower.fullname" . }}-approval
data:
  approval.txt: "{{ .Values.passmower.texts.approval.content }}"
{{- end }}
---
{{- if not .Values.passmower.texts.disable_frontend_edit.configMapRef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "passmower.fullname" . }}-disable-frontend-edit
data:
  disable_frontend_edit.md: "{{ .Values.passmower.texts.disable_frontend_edit.content }}"
{{- end }}
---
{{- if not .Values.passmower.texts.emails.configMapRef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "passmower.fullname" . }}-email-templates
data:
  link.subject: "{{ .Values.passmower.texts.emails.login_link.subject }}"
  link.txt: "{{ .Values.passmower.texts.emails.login_link.text }}"
  link.ejs: "{{ .Values.passmower.texts.emails.login_link.body }}"
  tos.subject: "{{ .Values.passmower.texts.emails.terms_of_service.subject }}"
  tos.txt: "{{ .Values.passmower.texts.emails.terms_of_service.text }}"
  tos.ejs: "{{ .Values.passmower.texts.emails.terms_of_service.body }}"
{{- end }}
